using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace ProjectName.Core.Interfaces;

/// <summary>
/// The contract for Phase P (Plan) and Phase C (Check).
/// I ensure the LLM complies with the defined cognitive structure.
/// </summary>
public interface IPlanner
{
    /// <summary>
    /// Phase P: Decomposes a messy intent into a monotonic sequence of steps.
    /// </summary>
    /// <param name="intent">The user's intent or goal.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A plan result containing the goal and execution steps.</returns>
    Task<PlanResult> CreatePlanAsync(string intent, CancellationToken ct = default);

    /// <summary>
    /// Phase C: Audits the artifacts generated by the Body against the original intent.
    /// </summary>
    /// <param name="intent">The original intent.</param>
    /// <param name="executionLog">The execution log to validate.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A validation result as JSON.</returns>
    Task<string> ValidateOutcomeAsync(string intent, string executionLog, CancellationToken ct = default);
}

/// <summary>
/// Represents the result of creating a plan.
/// </summary>
public sealed record PlanResult
{
    /// <summary>
    /// Gets the refined goal statement.
    /// </summary>
    public required string Goal { get; init; }

    /// <summary>
    /// Gets the reasoning or analysis behind the plan.
    /// </summary>
    public required string Analysis { get; init; }

    /// <summary>
    /// Gets the list of execution steps.
    /// </summary>
    public required IReadOnlyList<PlanStep> Steps { get; init; }
}

/// <summary>
/// Represents a single step in an execution plan.
/// </summary>
public sealed record PlanStep
{
    /// <summary>
    /// Gets the execution order of this step.
    /// </summary>
    public required int Order { get; init; }

    /// <summary>
    /// Gets a description of the action to perform.
    /// </summary>
    public required string Action { get; init; }

    /// <summary>
    /// Gets the tool to use for this step.
    /// </summary>
    public required string Tool { get; init; }

    /// <summary>
    /// Gets the tool arguments as a JSON string.
    /// </summary>
    public string ArgumentsJson { get; init; } = "{}";
}